### ISSUE TITLE
open the hidden source of ${template} in 3 files

### ISSUE THREAD

**Issue by javagrails** [grails-plugins/grails-angular2-scaffolding#6]
grails-angular-scaffolding/src/main/templates/angular/views/
  list.component.html
  persist.component.html
  show.component.html

-- above 3 files contains a variable ${template}.
-- even if templates are installed by command [ grails ngInstallTemplates ] then in src folder above 3 files contains the variable ${template}, actually this variable generate table,form elements and single object view. 
-- at this moment after generating developer have to add css on those generated  table,form elements and single object view.
-- my suggestion is that if those html generating codes are directly inserted instead of ${template} variable then it would be easy for developers to customize the view of any doamin.

**Comment by jameskleeh** [comment]
@javagrails The template is dynamically built based on your domain classes, so it is not possible to have static content in replacement of the `${template}`. If you would like to customize the HTML that gets generated, see the section on customization.

https://grails-plugins.github.io/grails-angular-scaffolding/latest/#_customization
